spring.application.name=User_TO_DO_Task
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp
server.port=8082
spring.datasource.driver-class-name:com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/my_database
spring.datasource.username=root
spring.datasource.password=vivek6200
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
